core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    SaleView,
    NewView,
    # home,
)

# from django.conf.urls import include, url

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('sale/', SaleView.as_view(), name='sale'),
    path('new/', NewView.as_view(), name='new'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
]

core/models.py
from django.db.models.expressions import F
from core.forms import DELIVERY
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField
import uuid


DELIVERY_A = 4000
DELIVERY_B = 5500


CATEGORY_CHOICES = (
    ('CH', 'Чийгшүүлэгч тос'),
    ('TS', 'Цэвэрлэгч'),
    ('TO', 'Тонер'),
    ('NT', 'Нарны тос'),
    ('HE', 'Хөгшрөлтийн эсрэг'),
    ('GU', 'Гуужуулагч'),
    ('ES', 'Эссэнц'),
    ('SE', 'Серум'),
    ('UA', 'Үс арчилгаа'),
    ('BA', 'Бие арчилгаа'),
    ('MA', 'Маск'),
    ('NB', 'Нүүрний будаг'),
    ('ZT', 'Зовхины тос'),
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)


class Carousel(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField()
    description = models.TextField(blank=True)
    button = models.CharField(max_length=50, blank=True)
    url = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    stock_amount = models.IntegerField(null=False)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    sold_out = models.BooleanField(default=False)
    special = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })

    def order_item(self):
        self.stock_amount = self.stock_amount - 1
        self.save()


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    uuid = models.CharField(unique=True, max_length=6, null=True)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    delivery_fee = models.CharField(max_length=5, blank=True, null=True)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    payment_received = models.BooleanField(default=False)
    contact = models.IntegerField(blank=True, null=True)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    address_detail = models.CharField(max_length=200)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def save(self, *args, **kwargs):
        if not self.pk:
            # This code only happens if the objects is
            # not in the database yet. Otherwise it would
            # have pk
            self.uuid = uuid.uuid4().hex[:6].upper()
        super(Order, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.username

    def get_items(self):
        return self.items

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        if self.delivery_fee == "a":
            return total + DELIVERY_A
        elif self.delivery_fee == "b":
            return total + DELIVERY_B
        else:
            return total

    def get_delivery_fee(self):
        if self.delivery_fee == "a":
            return DELIVERY_A
        elif self.delivery_fee == "b":
            return DELIVERY_B
        else:
            return None


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    duureg = models.CharField(max_length=100)
    khoroo_khotkhon = models.CharField(max_length=100)
    bair = models.CharField(max_length=100)
    orts = models.CharField(max_length=100)
    davhar = models.CharField(max_length=100)
    toot = models.CharField(max_length=100)
    code = models.CharField(max_length=100)
    nemelt = models.CharField(max_length=150)

    def get_string(self):
        return (self.duureg + self.khoroo_khotkhon)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/home.html
{% extends "base.html" %}
{% load humanize %}
{% block content %}
<main>
  <div class="container" style="min-width: 100%; padding: 0;">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5"
      style="background: #080705!important; margin: 0%!important;">

      <!-- Navbar brand -->
      <!-- <span class="navbar-brand">Ангилал:</span> -->

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav" style="margin-bottom: 0;">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <!-- <li class="nav-item active">
            <a class="nav-link" href="#">All
              <span class="sr-only">(current)</span>
            </a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link" href="/new">Шинэ брэнд</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/sale">Хямдралтай</a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="#">Арьсны асуудал</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Арьсны төрөл</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Бүтээгдэхүүний төрөл</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Мэдээлэл</a>
          </li> -->


        </ul>
        <!-- Links -->

        <!-- <form class="form-inline">
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Хайх" aria-label="Search">
          </div>
        </form> -->
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--/.Carousel-->
    <div id="myCarouselOuter">
      <div id="myCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel"
        style="margin-bottom:20px; margin-top: 0; height: 300px;">
        <!-- <div class="carousel-indicators">
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true"
          aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div> -->
        <div class="carousel-inner">
          {% for carousel in carousel %}
          <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}"
            style="background-image: url({{ carousel.image.url }});">
            <!-- <img src="{{ carousel.image.url }}" alt="Responsive image" focusable="false"> -->
            <div class="container">
              <div class="carousel-caption text-start">
                <h1>{{ carousel.title }}</h1>
                <p>{{ carousel.description }}</p>
                {% if carousel.button != "" %}
                <p><a class="btn btn-lg btn-primary" style="background-color: #080705!important;" href="#">
                    {{ carousel.button }}</a>
                </p>
                {% endif %}
              </div>
            </div>

          </div>
          {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>

    <!--/.Carousel-->
    <h2 style="align-content: center; position:relative; width: 100%; margin: auto; text-align: center;"> Эрэлттэй </h2>
    <!--/.Horizontal scroll-->
    <div class="scrolling-wrapper">
      {% for item in special %}
      <div class="card1">

        <div class="view overlay">
          <img src="{{ item.image.url }}" class="card-img-top">
          <a href="{{ item.get_absolute_url }}">
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>

        <div class="card-body text-center">
          <a href="" class="grey-text">
            <h5>{{ item.get_category_display }}</h5>
          </a>
          <h5>
            <strong>
              <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                <!-- <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span> -->
              </a>
            </strong>
          </h5>

          <h4 class="font-weight-bold black-text">
            <strong>₮
              {% if item.discount_price %}
              {{ item.discount_price|floatformat:0|intcomma }}
              {% else %}
              {{ item.price|floatformat:0|intcomma}}
              {% endif %}
            </strong>
          </h4>

        </div>

      </div>
      {% endfor %}
    </div>
    <!--/.Horizontal scroll-->
    <h2
      style="align-content: center; position:relative; width: 100%; margin: auto; text-align: center; padding-bottom: 10px;">
      Бүтээгдэхүүнүүд </h2>
    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      <div class="row wow fadeIn">

        {% for item in item %}
        <div class="col-lg-3 col-md-6 mb-4">

          <div class="card" style="height: 350px; width: 300px;">

            <div class="view overlay">
              <img src="{{ item.image.url }}" class="card-img-top">
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>

            <div class="card-body text-center">
              <a href="" class="grey-text">
                <h5>{{ item.get_category_display }}</h5>
              </a>
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                    <!-- <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span> -->
                  </a>
                </strong>
              </h5>

              <h4 class="font-weight-bold black-text">
                <strong>₮
                  {% if item.discount_price %}
                  {{ item.discount_price|floatformat:0|intcomma }}
                  {% else %}
                  {{ item.price|floatformat:0|intcomma }}
                  {% endif %}
                </strong>
              </h4>

            </div>

          </div>

        </div>
        {% endfor %}
      </div>

    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->

    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}

  </div>
</main>

{% endblock content %}

{% block extra_scripts %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock extra_scripts %}

templates/navbar.html
{% load cart_template_tags %}
{% load static %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="/">
      <img src="/static/img/miru_copy.png" alt="logo" style="max-height: 30px;">
      <strong class="black-text">MIRUSKINCARE</strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        {% comment %} <li class="nav-item active">
          <a class="nav-link waves-effect" href="/">Нүүр
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="/checkout">
            Худалдан авах</a>
        </li> {% endcomment %}
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
            <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
            <i class="fas fa-shopping-cart"></i>
            <span class="clearfix d-none d-sm-inline-block"> Сагс </span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'core:payment' %}" class="nav-link waves-effect">
            <!-- <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span> -->
            <i class="fas fa-barcode"></i>
            <span class="clearfix d-none d-sm-inline-block"> Миний захиалга </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
            <span class="clearfix d-none d-sm-inline-block"> Гарах </span>
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_login' %}">
            <span class="clearfix d-none d-sm-inline-block"> Нэвтрэх </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
            <span class="clearfix d-none d-sm-inline-block"> Бүртгүүлэх </span>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>

  </div>
</nav>

templates/new.html
{% extends "base.html" %}
{% load humanize %}
{% block content %}
<main>
    <div class="container" style="min-width: 100%; padding: 0;">
        <!--/.Horizontal scroll-->
        <h2
            style="align-content: center; position:relative; width: 100%; margin: auto; text-align: center; padding-bottom: 10px; padding-top: 20px;">
            Шинэ бүтээгдэхүүнүүд </h2>
        <!--Section: Products v.3-->
        <section class="text-center mb-4">

            <div class="row wow fadeIn">

                {% for item in item %}
                <div class="col-lg-3 col-md-6 mb-4">

                    <div class="card" style="width: 300px; height: 350px;">

                        <div class="view overlay">
                            <img src="{{ item.image.url }}" class="card-img-top">
                            <a href="{{ item.get_absolute_url }}">
                                <div class="mask rgba-white-slight"></div>
                            </a>
                        </div>

                        <div class="card-body text-center">
                            <a href="" class="grey-text">
                                <h5>{{ item.get_category_display }}</h5>
                            </a>
                            <h5>
                                <strong>
                                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                                        <!-- <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span> -->
                                    </a>
                                </strong>
                            </h5>

                            <h4 class="font-weight-bold black-text">
                                <strong>₮
                                    {% if item.discount_price %}
                                    {{ item.discount_price|floatformat:0|intcomma }}
                                    {% else %}
                                    {{ item.price|floatformat:0|intcomma }}
                                    {% endif %}
                                </strong>
                            </h4>

                        </div>

                    </div>

                </div>
                {% endfor %}
            </div>

        </section>
        <!--Section: Products v.3-->

        <!--Pagination-->

        {% if is_paginated %}
        <nav class="d-flex justify-content-center wow fadeIn">
            <ul class="pagination pg-blue">

                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                {% endif %}

                <li class="page-item active">
                    <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                        <span class="sr-only">(current)</span>
                    </a>
                </li>

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}

    </div>
</main>

{% endblock content %}

{% block extra_scripts %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
{% endblock extra_scripts %}

templates/order_snippet.html
{% load humanize %}
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Таны сагс</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
                <!-- <small class="text-muted">{{ order_item.item.description}}</small> -->
            </div>
            <span class="text-muted">₮{{ order_item.get_final_price|intcomma }}</span>
        </li>
        {% endfor %}
        {% if order.coupon %}
        <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>{{ order.coupon.code }}</small>
            </div>
            <span class="text-success">-₮{{ order.coupon.amount|intcomma }}</span>
        </li>
        {% endif %}
        {% if order.get_delivery_fee != None %}
        <li class="list-group-item d-flex justify-content-between">
            <span>Хүргэлт</span>
            <span class="text-muted">₮{{ order.get_delivery_fee|intcomma }}</span>
            <!-- <strong>₮{{ order.get_delivery_fee|intcomma }}</strong> -->
        </li>
        {% endif %}
        <li class="list-group-item d-flex justify-content-between">
            <span>Нийт (хүргэлтийн үнэ нэмэгдэнэ)</span>
            <strong>₮{{ order.get_total|intcomma }}</strong>
        </li>
    </ul>

    <!-- {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %} -->

</div>

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}

templates/sale.html
{% extends "base.html" %}
{% load humanize %}
{% block content %}
<main>
    <div class="container" style="min-width: 100%; padding: 0;">
        <!--/.Horizontal scroll-->
        <h2
            style="align-content: center; position:relative; width: 100%; margin: auto; text-align: center; padding-bottom: 10px; padding-top: 20px;">
            Хямдралтай </h2>
        <!--Section: Products v.3-->
        <section class="text-center mb-4">
            {% if item %}
            <div class="row wow fadeIn">

                {% for item in item %}
                <div class="col-lg-3 col-md-6 mb-4">

                    <div class="card" style="height: 350px; width: 300px;">

                        <div class="view overlay">
                            <img src="{{ item.image.url }}" class="card-img-top">
                            <a href="{{ item.get_absolute_url }}">
                                <div class="mask rgba-white-slight"></div>
                            </a>
                        </div>

                        <div class="card-body text-center">
                            <a href="" class="grey-text">
                                <h5>{{ item.get_category_display }}</h5>
                            </a>
                            <h5>
                                <strong>
                                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                                        <!-- <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span> -->
                                    </a>
                                </strong>
                            </h5>

                            <h4 class="font-weight-bold black-text">
                                <strong>₮
                                    {% if item.discount_price %}
                                    {{ item.discount_price|floatformat:0|intcomma }}
                                    {% else %}
                                    {{ item.price|floatformat:0|intcomma }}
                                    {% endif %}
                                </strong>
                            </h4>

                        </div>

                    </div>

                </div>
                {% endfor %}
            </div>
            {% else %}
            <h3
                style="align-content: center; position:relative; width: 100%; margin: auto; text-align: center; padding-bottom: 10px; padding-top: 20px;">
                Одоогоор хямдарсан бүтээгдэхүүн байхгүй байна. Дараа дахин шалгаарай. </h3>
            {% endif %}
        </section>
        <!--Section: Products v.3-->

        <!--Pagination-->

        {% if is_paginated %}
        <nav class="d-flex justify-content-center wow fadeIn">
            <ul class="pagination pg-blue">

                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                {% endif %}

                <li class="page-item active">
                    <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                        <span class="sr-only">(current)</span>
                    </a>
                </li>

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}

    </div>
</main>

{% endblock content %}

{% block extra_scripts %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
{% endblock extra_scripts %}

templates/scripts.html
{% load static %}

<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();
</script>